linters:
  presets:
    # from: golangci-lint help linters
    - bugs
    - comment
    # - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    # - style
    - test
    - unused
  disable:
    - testpackage
    - paralleltest
    # deprecated:
    - scopelint
    - maligned
    - exhaustivestruct
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
